#
# Makefile for the touchscreen drivers.
#
# Each configuration option enables a list of files.


obj-y      += rockchip_pwm_capture.o yc_arrqueue.o
obj-y      += heart_rate.o
obj-y      += rockchip_custom.o
obj-y 	   += matrix_scankey.o
